name: seeded_noisy_conala
stages:
  - name: Noisy CoNaLa, 60% threshold, Seed 1
    type: train
    parameters:
      seed: 1
    dataset:
      parameters:
        mined_filepath: datasets/conala/mined.jsonl
        train_filepath: datasets/conala/train.json
        threshold: 0.6
      format: conala_noisy
    model:
      uri: microsoft/CodeGPT-small-py-adaptedGPT2
      source: huggingface
  - name: Noisy CoNaLa, 60% threshold, Seed 2
    type: train
    parameters:
      seed: 2
    dataset:
      parameters:
        mined_filepath: datasets/conala/mined.jsonl
        train_filepath: datasets/conala/train.json
        threshold: 0.6
      format: conala_noisy
    model:
      uri: microsoft/CodeGPT-small-py-adaptedGPT2
      source: huggingface
  - name: Noisy CoNaLa, 50% threshold, Seed 1
    type: train
    parameters:
      seed: 1
    dataset:
      parameters:
        mined_filepath: datasets/conala/mined.jsonl
        train_filepath: datasets/conala/train.json
        threshold: 0.5
      format: conala_noisy
    model:
      uri: microsoft/CodeGPT-small-py-adaptedGPT2
      source: huggingface
  - name: Noisy CoNaLa, 50% threshold, Seed 2
    type: train
    parameters:
      seed: 2
    dataset:
      parameters:
        mined_filepath: datasets/conala/mined.jsonl
        train_filepath: datasets/conala/train.json
        threshold: 0.5
      format: conala_noisy
    model:
      uri: microsoft/CodeGPT-small-py-adaptedGPT2
      source: huggingface
  - name: Noisy CoNaLa, 40% threshold, Seed 1
    type: train
    parameters:
      seed: 1
    dataset:
      parameters:
        mined_filepath: datasets/conala/mined.jsonl
        train_filepath: datasets/conala/train.json
        threshold: 0.4
      format: conala_noisy
    model:
      uri: microsoft/CodeGPT-small-py-adaptedGPT2
      source: huggingface
  - name: Noisy CoNaLa, 40% threshold, Seed 2
    type: train
    parameters:
      seed: 2
    dataset:
      parameters:
        mined_filepath: datasets/conala/mined.jsonl
        train_filepath: datasets/conala/train.json
        threshold: 0.4
      format: conala_noisy
    model:
      uri: microsoft/CodeGPT-small-py-adaptedGPT2
      source: huggingface
  - name: Noisy CoNaLa, 30% threshold, Seed 1
    type: train
    parameters:
      seed: 1
    dataset:
      parameters:
        mined_filepath: datasets/conala/mined.jsonl
        train_filepath: datasets/conala/train.json
        threshold: 0.3
      format: conala_noisy
    model:
      uri: microsoft/CodeGPT-small-py-adaptedGPT2
      source: huggingface
  - name: Noisy CoNaLa, 30% threshold, Seed 2
    type: train
    parameters:
      seed: 2
    dataset:
      parameters:
        mined_filepath: datasets/conala/mined.jsonl
        train_filepath: datasets/conala/train.json
        threshold: 0.3
      format: conala_noisy
    model:
      uri: microsoft/CodeGPT-small-py-adaptedGPT2
      source: huggingface